// Industry → Skill demand mapping
// Each skill has a demand weight (0-100) representing how important it is for that industry.
// Only skills present in SKILL_CATEGORIES are included.

export const industrySkillDemand: Record<string, Record<string, number>> = {
  "BPO / Outsourcing": {
    communication: 95,
    "customer service": 90,
    teamwork: 80,
    "time management": 75,
    adaptability: 70,
    "microsoft office": 65,
    "google workspace": 60,
    excel: 55,
    "problem solving": 70,
    leadership: 40,
    zendesk: 50,
    salesforce: 45,
    "data entry": 60,
    "public speaking": 30,
    negotiation: 25,
  },
  "IT / Software": {
    javascript: 90,
    react: 85,
    typescript: 80,
    git: 75,
    "node.js": 70,
    css: 65,
    html: 65,
    "next.js": 60,
    python: 60,
    sql: 70,
    java: 55,
    php: 40,
    "problem solving": 80,
    teamwork: 60,
    communication: 50,
    figma: 40,
    jira: 55,
    "quality assurance": 50,
  },
  "Banking / Finance": {
    excel: 90,
    "microsoft office": 85,
    "data entry": 80,
    accounting: 85,
    bookkeeping: 75,
    communication: 70,
    "data analysis": 65,
    "problem solving": 60,
    "time management": 55,
    quickbooks: 50,
    sap: 60,
    payroll: 45,
    sql: 40,
    "power bi": 45,
  },
  Healthcare: {
    communication: 85,
    "customer service": 70,
    "data entry": 75,
    "microsoft office": 65,
    teamwork: 70,
    "time management": 60,
    "problem solving": 55,
    "quality assurance": 50,
    adaptability: 60,
    excel: 45,
    research: 40,
  },
  Education: {
    communication: 90,
    "public speaking": 85,
    "content writing": 70,
    "google workspace": 75,
    "microsoft office": 65,
    canva: 60,
    leadership: 55,
    "problem solving": 50,
    teamwork: 55,
    research: 60,
    copywriting: 35,
    figma: 25,
    "time management": 50,
  },
  "Retail / E-commerce": {
    "customer service": 90,
    communication: 80,
    canva: 55,
    "social media management": 75,
    copywriting: 60,
    "content writing": 55,
    "google analytics": 65,
    seo: 60,
    excel: 50,
    "data entry": 45,
    salesforce: 40,
    hubspot: 50,
    "market research": 55,
  },
  Manufacturing: {
    excel: 75,
    "data entry": 70,
    "quality assurance": 80,
    sap: 65,
    "microsoft office": 60,
    "problem solving": 65,
    teamwork: 55,
    communication: 50,
    "project management": 55,
    "time management": 50,
    "data analysis": 40,
  },
  "Real Estate": {
    communication: 85,
    negotiation: 80,
    "customer service": 70,
    canva: 50,
    "social media management": 55,
    excel: 60,
    "microsoft office": 55,
    salesforce: 45,
    copywriting: 40,
    "market research": 55,
    "public speaking": 45,
  },
  Telecommunications: {
    "customer service": 85,
    communication: 80,
    "technical support": 75,
    "problem solving": 70,
    "microsoft office": 55,
    sql: 50,
    "data entry": 45,
    teamwork: 55,
    adaptability: 50,
    "data analysis": 40,
    zendesk: 45,
    jira: 35,
  },
  "Media / Advertising": {
    canva: 80,
    figma: 70,
    copywriting: 85,
    "content writing": 80,
    "social media management": 90,
    "google analytics": 65,
    seo: 60,
    photoshop: 55,
    illustrator: 50,
    communication: 60,
    "data visualization": 35,
    "market research": 50,
    "public speaking": 30,
  },
  Government: {
    "microsoft office": 80,
    communication: 75,
    "data entry": 70,
    excel: 65,
    "public speaking": 50,
    "google workspace": 45,
    accounting: 40,
    bookkeeping: 40,
    "time management": 50,
    leadership: 45,
    "problem solving": 50,
    research: 55,
    "project management": 40,
  },
  "Hospitality / Tourism": {
    "customer service": 95,
    communication: 90,
    adaptability: 75,
    teamwork: 70,
    "time management": 65,
    "public speaking": 50,
    "microsoft office": 40,
    "social media management": 45,
    canva: 35,
    "problem solving": 55,
    negotiation: 30,
  },
};
