// Major Philippine universities and colleges for school autocomplete

export const PH_SCHOOLS: string[] = [
  "Adamson University",
  "Ateneo de Davao University",
  "Ateneo de Manila University",
  "Batangas State University",
  "Benilde - De La Salle College of Saint Benilde",
  "Bicol University",
  "Bulacan State University",
  "Cavite State University",
  "Central Luzon State University",
  "Central Mindanao University",
  "Centro Escolar University",
  "Colegio de San Juan de Letran",
  "De La Salle University",
  "De La Salle - College of Saint Benilde",
  "Don Honorio Ventura State University",
  "Far Eastern University",
  "FEU Institute of Technology",
  "Holy Angel University",
  "Lyceum of the Philippines University",
  "Manuel S. Enverga University Foundation",
  "Mapúa University",
  "Mariano Marcos State University",
  "Mindanao State University",
  "Miriam College",
  "National University",
  "Northwestern University",
  "Notre Dame of Dadiangas University",
  "Nueva Ecija University of Science and Technology",
  "Our Lady of Fatima University",
  "Pamantasan ng Lungsod ng Maynila",
  "Pangasinan State University",
  "Philippine Normal University",
  "Polytechnic University of the Philippines",
  "Saint Louis University",
  "San Beda University",
  "San Sebastian College – Recoletos",
  "Silliman University",
  "St. Paul University Manila",
  "STI College",
  "Technological University of the Philippines",
  "Tarlac State University",
  "University of Cebu",
  "University of San Carlos",
  "University of San Jose – Recoletos",
  "University of Santo Tomas",
  "University of Southeastern Philippines",
  "University of the East",
  "University of the Philippines Diliman",
  "University of the Philippines Los Baños",
  "University of the Philippines Manila",
  "University of the Philippines Visayas",
  "Visayas State University",
  "West Visayas State University",
  "Xavier University – Ateneo de Cagayan",
];
