// Skill affinity map: each skill maps to related skills for intelligent suggestions.
// When a user selects a skill, its affinities get +1 score. Top 5 unselected shown.
// Uses canonical skill names from PRD taxonomy (ph_job_app_skill_taxonomy.xlsx).
// Derived from subcategory proximity + cross-cluster bridges.

export const SKILL_AFFINITIES: Record<string, string[]> = {
  // ─── DEV: Software Development ───
  "HTML": ["CSS", "JavaScript", "React", "TypeScript", "Tailwind CSS"],
  "CSS": ["HTML", "JavaScript", "Tailwind CSS", "SASS/SCSS", "Figma"],
  "JavaScript": ["TypeScript", "React", "Node.js", "HTML", "CSS"],
  "TypeScript": ["JavaScript", "React", "Next.js", "Node.js", "Git"],
  "React": ["TypeScript", "Next.js", "JavaScript", "Tailwind CSS", "Git"],
  "Next.js": ["React", "TypeScript", "Node.js", "Tailwind CSS", "Git"],
  "Vue.js": ["JavaScript", "TypeScript", "HTML", "CSS", "Node.js"],
  "Angular": ["TypeScript", "JavaScript", "HTML", "CSS", "Node.js"],
  "Node.js": ["JavaScript", "TypeScript", "SQL", "REST API Development", "Git"],
  "Python": ["SQL", "Git", "REST API Development", "Docker", "Data Cleaning & Wrangling"],
  "Java": ["SQL", "Git", "Docker", "REST API Development", "AWS"],
  "PHP": ["Laravel", "SQL", "MySQL", "HTML", "CSS"],
  "Laravel": ["PHP", "MySQL", "SQL", "REST API Development", "Git"],
  "Ruby on Rails": ["PostgreSQL", "SQL", "Git", "REST API Development", "Docker"],
  "C#/.NET": ["SQL", "Azure", "Git", "REST API Development", "Docker"],
  "Go (Golang)": ["Docker", "Kubernetes", "REST API Development", "PostgreSQL", "Git"],
  "SQL": ["PostgreSQL", "MySQL", "Python", "Node.js", "REST API Development"],
  "PostgreSQL": ["SQL", "Node.js", "Python", "Docker", "Git"],
  "MySQL": ["SQL", "PHP", "Laravel", "Node.js", "Docker"],
  "MongoDB": ["Node.js", "REST API Development", "JavaScript", "Docker", "Git"],
  "Git": ["JavaScript", "TypeScript", "Docker", "CI/CD Pipelines", "Linux / CLI"],
  "Docker": ["Kubernetes", "CI/CD Pipelines", "AWS", "Linux / CLI", "Git"],
  "AWS": ["Docker", "CI/CD Pipelines", "Terraform", "Linux / CLI", "Kubernetes"],
  "Google Cloud (GCP)": ["Docker", "Kubernetes", "BigQuery", "Terraform", "CI/CD Pipelines"],
  "Azure": ["C#/.NET", "Docker", "Kubernetes", "Terraform", "CI/CD Pipelines"],
  "REST API Development": ["Node.js", "Python", "SQL", "GraphQL", "Git"],
  "GraphQL": ["REST API Development", "React", "Node.js", "TypeScript", "Next.js"],
  "React Native": ["React", "TypeScript", "JavaScript", "Flutter", "Git"],
  "Flutter": ["React Native", "Firebase", "Git", "REST API Development", "Kotlin (Android)"],
  "Swift (iOS)": ["React Native", "Git", "Firebase", "REST API Development", "Flutter"],
  "Kotlin (Android)": ["React Native", "Flutter", "Git", "Firebase", "REST API Development"],
  "WordPress": ["PHP", "HTML", "CSS", "SEO", "Content Writing"],
  "Shopify / Liquid": ["HTML", "CSS", "JavaScript", "E-Commerce Management", "Shopify Marketing"],
  "CI/CD Pipelines": ["Docker", "Git", "AWS", "Kubernetes", "Linux / CLI"],
  "Linux / CLI": ["Docker", "Git", "AWS", "CI/CD Pipelines", "Kubernetes"],
  "Agile / Scrum": ["Git", "Project Management (Asana/Trello)", "Unit Testing", "CI/CD Pipelines", "Figma"],
  "Unit Testing": ["JavaScript", "TypeScript", "Git", "CI/CD Pipelines", "React"],
  "Tailwind CSS": ["React", "Next.js", "CSS", "HTML", "TypeScript"],
  "SASS/SCSS": ["CSS", "HTML", "Tailwind CSS", "React", "JavaScript"],
  "Webpack / Vite": ["JavaScript", "TypeScript", "React", "Next.js", "SASS/SCSS"],
  "Firebase": ["React", "Flutter", "React Native", "Node.js", "JavaScript"],
  "Redis": ["Node.js", "Docker", "PostgreSQL", "REST API Development", "AWS"],
  "Kubernetes": ["Docker", "AWS", "CI/CD Pipelines", "Terraform", "Linux / CLI"],
  "Terraform": ["AWS", "Docker", "Kubernetes", "CI/CD Pipelines", "Google Cloud (GCP)"],
  "Cybersecurity Basics": ["Linux / CLI", "AWS", "Docker", "CI/CD Pipelines", "Git"],

  // ─── DES: Design & Creative ───
  "Figma": ["UI Design", "UX Design", "Adobe Photoshop", "Wireframing & Prototyping", "Design Systems"],
  "Adobe Photoshop": ["Adobe Illustrator", "Figma", "Canva", "Brand Identity Design", "Typography"],
  "Adobe Illustrator": ["Adobe Photoshop", "Figma", "Brand Identity Design", "Typography", "Print Design"],
  "Adobe InDesign": ["Adobe Illustrator", "Print Design", "Typography", "Brand Identity Design", "Adobe Photoshop"],
  "Adobe XD": ["Figma", "UI Design", "UX Design", "Wireframing & Prototyping", "Adobe Photoshop"],
  "Sketch": ["Figma", "UI Design", "UX Design", "Wireframing & Prototyping", "Adobe XD"],
  "Canva": ["Social Media Graphics", "Adobe Photoshop", "Presentation Design", "Brand Identity Design", "Social Media Management"],
  "Adobe After Effects": ["Adobe Premiere Pro", "Lottie / Micro-animations", "DaVinci Resolve", "UI Design", "CapCut"],
  "Adobe Premiere Pro": ["Adobe After Effects", "DaVinci Resolve", "CapCut", "Script Writing (Video)", "YouTube Marketing"],
  "DaVinci Resolve": ["Adobe Premiere Pro", "Adobe After Effects", "CapCut", "Color Theory", "Photography"],
  "CapCut": ["Adobe Premiere Pro", "TikTok Marketing", "Social Media Graphics", "Video Thumbnails & Banners", "DaVinci Resolve"],
  "UI Design": ["UX Design", "Figma", "Design Systems", "Wireframing & Prototyping", "Responsive Design"],
  "UX Design": ["UI Design", "UX Research", "Wireframing & Prototyping", "Figma", "Design Systems"],
  "UX Research": ["UX Design", "UI Design", "Wireframing & Prototyping", "A/B Testing", "Design Systems"],
  "Wireframing & Prototyping": ["Figma", "UI Design", "UX Design", "Design Systems", "UX Research"],
  "Design Systems": ["Figma", "UI Design", "UX Design", "Responsive Design", "Wireframing & Prototyping"],
  "Brand Identity Design": ["Adobe Illustrator", "Typography", "Color Theory", "Adobe Photoshop", "Print Design"],
  "Typography": ["Brand Identity Design", "Adobe Illustrator", "Color Theory", "Print Design", "Figma"],
  "Color Theory": ["Typography", "Brand Identity Design", "UI Design", "Adobe Photoshop", "Adobe Illustrator"],
  "Print Design": ["Adobe InDesign", "Adobe Illustrator", "Typography", "Brand Identity Design", "Adobe Photoshop"],
  "3D Modeling (Blender)": ["Adobe After Effects", "Illustration (Digital)", "Adobe Photoshop", "Lottie / Micro-animations", "Photography"],
  "Photography": ["Adobe Photoshop", "Adobe Illustrator", "DaVinci Resolve", "Canva", "Color Theory"],
  "Illustration (Digital)": ["Adobe Illustrator", "Adobe Photoshop", "Figma", "3D Modeling (Blender)", "Brand Identity Design"],
  "Responsive Design": ["UI Design", "CSS", "Figma", "Design Systems", "Accessibility Design (a11y)"],
  "Accessibility Design (a11y)": ["UX Design", "UI Design", "Responsive Design", "Design Systems", "Figma"],
  "Presentation Design": ["Canva", "Adobe Photoshop", "Typography", "Infographic Design", "Brand Identity Design"],
  "Infographic Design": ["Canva", "Adobe Illustrator", "Data Storytelling", "Presentation Design", "Adobe Photoshop"],
  "Social Media Graphics": ["Canva", "Social Media Management", "Adobe Photoshop", "Video Thumbnails & Banners", "Brand Identity Design"],
  "Video Thumbnails & Banners": ["Social Media Graphics", "Canva", "Adobe Photoshop", "YouTube Marketing", "Adobe Premiere Pro"],
  "Lottie / Micro-animations": ["Adobe After Effects", "UI Design", "Figma", "Design Systems", "CSS"],

  // ─── DATA: Data & Analytics ───
  "Excel (Advanced)": ["Power BI", "Google Sheets (Advanced)", "SQL (Data Analysis)", "Data Cleaning & Wrangling", "Financial Analysis"],
  "Google Sheets (Advanced)": ["Excel (Advanced)", "Google Data Studio / Looker", "Data Cleaning & Wrangling", "Google Workspace", "SQL (Data Analysis)"],
  "SQL (Data Analysis)": ["Excel (Advanced)", "Python (Data Science)", "Power BI", "Tableau", "Data Cleaning & Wrangling"],
  "Python (Data Science)": ["Pandas / NumPy", "SQL (Data Analysis)", "Machine Learning (Basics)", "Data Cleaning & Wrangling", "Statistical Analysis"],
  "R Programming": ["Statistical Analysis", "Python (Data Science)", "Data Cleaning & Wrangling", "Tableau", "A/B Testing"],
  "Tableau": ["Power BI", "SQL (Data Analysis)", "Excel (Advanced)", "Data Storytelling", "Google Data Studio / Looker"],
  "Power BI": ["Tableau", "Excel (Advanced)", "SQL (Data Analysis)", "Data Storytelling", "Google Data Studio / Looker"],
  "Google Data Studio / Looker": ["Google Analytics", "Power BI", "Tableau", "Google Sheets (Advanced)", "BigQuery"],
  "Data Cleaning & Wrangling": ["Python (Data Science)", "Pandas / NumPy", "SQL (Data Analysis)", "Excel (Advanced)", "ETL / Data Pipelines"],
  "Statistical Analysis": ["Python (Data Science)", "R Programming", "A/B Testing", "Data Cleaning & Wrangling", "Pandas / NumPy"],
  "Machine Learning (Basics)": ["Python (Data Science)", "Deep Learning", "Pandas / NumPy", "Statistical Analysis", "NLP (Natural Language Processing)"],
  "Deep Learning": ["Machine Learning (Basics)", "Python (Data Science)", "NLP (Natural Language Processing)", "Computer Vision", "Pandas / NumPy"],
  "NLP (Natural Language Processing)": ["Machine Learning (Basics)", "Python (Data Science)", "Deep Learning", "Prompt Engineering", "AI Tools (ChatGPT, Claude, etc.)"],
  "Pandas / NumPy": ["Python (Data Science)", "Data Cleaning & Wrangling", "Machine Learning (Basics)", "SQL (Data Analysis)", "Statistical Analysis"],
  "ETL / Data Pipelines": ["SQL (Data Analysis)", "Python (Data Science)", "BigQuery", "Apache Spark", "Data Cleaning & Wrangling"],
  "BigQuery": ["Google Cloud (GCP)", "SQL (Data Analysis)", "Google Data Studio / Looker", "ETL / Data Pipelines", "Python (Data Science)"],
  "Apache Spark": ["ETL / Data Pipelines", "Python (Data Science)", "BigQuery", "SQL (Data Analysis)", "Data Cleaning & Wrangling"],
  "A/B Testing": ["Statistical Analysis", "Google Analytics", "Conversion Rate Optimization", "Data Storytelling", "Python (Data Science)"],
  "Data Storytelling": ["Tableau", "Power BI", "Infographic Design", "Presentation Design", "A/B Testing"],
  "Web Scraping": ["Python (Data Science)", "Data Cleaning & Wrangling", "REST API Development", "Pandas / NumPy", "SQL (Data Analysis)"],
  "Prompt Engineering": ["AI Tools (ChatGPT, Claude, etc.)", "NLP (Natural Language Processing)", "Content Writing", "Python (Data Science)", "Machine Learning (Basics)"],
  "AI Tools (ChatGPT, Claude, etc.)": ["Prompt Engineering", "Content Writing", "Python (Data Science)", "Data Cleaning & Wrangling", "NLP (Natural Language Processing)"],
  "Business Intelligence": ["Power BI", "Tableau", "SQL (Data Analysis)", "Excel (Advanced)", "Data Storytelling"],
  "Data Governance": ["Business Intelligence", "Compliance & Regulatory", "SQL (Data Analysis)", "ETL / Data Pipelines", "Data Cleaning & Wrangling"],
  "Computer Vision": ["Deep Learning", "Python (Data Science)", "Machine Learning (Basics)", "NLP (Natural Language Processing)", "Pandas / NumPy"],

  // ─── BPO: BPO & Customer Service ───
  "Customer Service (Voice)": ["Customer Service (Non-Voice)", "English Proficiency", "Neutral English Accent", "Conflict Resolution", "CRM Management"],
  "Customer Service (Non-Voice)": ["Customer Service (Voice)", "Email Support", "Live Chat Support", "Typing Speed (50+ WPM)", "CRM Management"],
  "Email Support": ["Live Chat Support", "Customer Service (Non-Voice)", "Typing Speed (50+ WPM)", "Zendesk", "Ticketing Systems"],
  "Live Chat Support": ["Email Support", "Customer Service (Non-Voice)", "Typing Speed (50+ WPM)", "Intercom", "Zendesk"],
  "Technical Support": ["Zendesk", "Ticketing Systems", "Freshdesk", "CRM Management", "Customer Service (Voice)"],
  "Zendesk": ["Freshdesk", "Ticketing Systems", "Technical Support", "CRM Management", "Salesforce Service Cloud"],
  "Freshdesk": ["Zendesk", "Ticketing Systems", "Technical Support", "CRM Management", "Intercom"],
  "Salesforce Service Cloud": ["CRM Management", "Zendesk", "Salesforce CRM", "Ticketing Systems", "Technical Support"],
  "Intercom": ["Live Chat Support", "Zendesk", "Freshdesk", "CRM Management", "Email Support"],
  "Quality Assurance (BPO)": ["Customer Service (Voice)", "CRM Management", "Content Moderation", "Ticketing Systems", "English Proficiency"],
  "Content Moderation": ["Quality Assurance (BPO)", "English Proficiency", "Community Management", "Social Media Management", "Typing Speed (50+ WPM)"],
  "English Proficiency": ["Neutral English Accent", "Customer Service (Voice)", "Typing Speed (50+ WPM)", "Content Writing", "ESL / TESOL Teaching"],
  "Neutral English Accent": ["English Proficiency", "Customer Service (Voice)", "Cold Calling", "Telemarketing", "Conflict Resolution"],
  "Typing Speed (50+ WPM)": ["Data Entry", "Email Support", "Live Chat Support", "Customer Service (Non-Voice)", "Transcription"],
  "CRM Management": ["Salesforce Service Cloud", "Zendesk", "Salesforce CRM", "Lead Generation", "Technical Support"],
  "Ticketing Systems": ["Zendesk", "Freshdesk", "Technical Support", "CRM Management", "Email Support"],
  "Conflict Resolution": ["Customer Service (Voice)", "Negotiation", "English Proficiency", "Neutral English Accent", "Account Management"],
  "Upselling / Cross-selling": ["Cold Calling", "Telemarketing", "Lead Generation", "Negotiation", "B2C Sales"],
  "Multilingual Support": ["English Proficiency", "Customer Service (Voice)", "Customer Service (Non-Voice)", "Content Moderation", "ESL / TESOL Teaching"],
  "Data Entry": ["Typing Speed (50+ WPM)", "Microsoft Office Suite", "Excel (Advanced)", "Google Workspace", "Data Cleaning & Wrangling"],

  // ─── MKT: Marketing & Content ───
  "SEO": ["Google Analytics", "Content Writing", "Semrush / Ahrefs", "Google Ads (SEM)", "Blog Writing"],
  "Google Ads (SEM)": ["Facebook/Meta Ads", "SEO", "Google Analytics", "Landing Page Optimization", "Conversion Rate Optimization"],
  "Facebook/Meta Ads": ["Google Ads (SEM)", "Social Media Management", "TikTok Marketing", "Google Analytics", "Landing Page Optimization"],
  "Google Analytics": ["SEO", "Google Ads (SEM)", "Google Tag Manager", "Google Data Studio / Looker", "A/B Testing"],
  "Social Media Management": ["Content Writing", "Canva", "Social Media Graphics", "Hootsuite / Buffer", "TikTok Marketing"],
  "Content Writing": ["Copywriting", "Blog Writing", "SEO", "Social Media Management", "Email Marketing"],
  "Copywriting": ["Content Writing", "Email Marketing", "Landing Page Optimization", "SEO", "Brand Strategy"],
  "Email Marketing": ["Mailchimp", "Copywriting", "Content Writing", "HubSpot", "Landing Page Optimization"],
  "Mailchimp": ["Email Marketing", "HubSpot", "Copywriting", "Landing Page Optimization", "Content Writing"],
  "HubSpot": ["Mailchimp", "Email Marketing", "CRM Management", "Lead Generation", "Salesforce CRM"],
  "WordPress (Content)": ["SEO", "Blog Writing", "Content Writing", "Google Analytics", "Copywriting"],
  "TikTok Marketing": ["Social Media Management", "CapCut", "Facebook/Meta Ads", "YouTube Marketing", "Influencer Marketing"],
  "YouTube Marketing": ["Adobe Premiere Pro", "TikTok Marketing", "Script Writing (Video)", "Social Media Management", "Video Thumbnails & Banners"],
  "Influencer Marketing": ["Social Media Management", "TikTok Marketing", "Brand Strategy", "Community Management", "Content Writing"],
  "Affiliate Marketing": ["E-Commerce Management", "SEO", "Shopify Marketing", "Landing Page Optimization", "Conversion Rate Optimization"],
  "Brand Strategy": ["Copywriting", "Brand Identity Design", "PR & Communications", "Market Research", "Social Media Management"],
  "Market Research": ["Statistical Analysis", "Google Analytics", "Brand Strategy", "A/B Testing", "Data Storytelling"],
  "PR & Communications": ["Brand Strategy", "Content Writing", "Copywriting", "Community Management", "Social Media Management"],
  "Podcast Production": ["Script Writing (Video)", "YouTube Marketing", "Adobe Premiere Pro", "Content Writing", "Community Management"],
  "Shopify Marketing": ["E-Commerce Management", "Facebook/Meta Ads", "Google Ads (SEM)", "SEO", "Shopify / Liquid"],
  "Landing Page Optimization": ["Conversion Rate Optimization", "Google Ads (SEM)", "Copywriting", "A/B Testing", "Facebook/Meta Ads"],
  "Conversion Rate Optimization": ["Landing Page Optimization", "A/B Testing", "Google Analytics", "Google Ads (SEM)", "Copywriting"],
  "Google Tag Manager": ["Google Analytics", "Google Ads (SEM)", "SEO", "Facebook/Meta Ads", "Conversion Rate Optimization"],
  "Hootsuite / Buffer": ["Social Media Management", "Canva", "Social Media Graphics", "Content Writing", "TikTok Marketing"],
  "Technical Writing": ["Content Writing", "Blog Writing", "REST API Development", "Instructional Design", "Copywriting"],
  "Blog Writing": ["Content Writing", "SEO", "Copywriting", "WordPress (Content)", "Social Media Management"],
  "Script Writing (Video)": ["Adobe Premiere Pro", "YouTube Marketing", "Podcast Production", "Copywriting", "Content Writing"],
  "Community Management": ["Social Media Management", "Content Moderation", "Content Writing", "Hootsuite / Buffer", "PR & Communications"],
  "Semrush / Ahrefs": ["SEO", "Google Analytics", "Google Ads (SEM)", "Content Writing", "Blog Writing"],
  "E-Commerce Management": ["Shopify Marketing", "Facebook/Meta Ads", "Google Ads (SEM)", "Inventory Management", "SEO"],

  // ─── VA: Virtual Assistance & Admin ───
  "Calendar Management": ["Email Management", "Microsoft Office Suite", "Google Workspace", "Meeting Minutes & Notes", "Time Management"],
  "Email Management": ["Calendar Management", "Microsoft Office Suite", "Google Workspace", "Client Communication", "Time Management"],
  "Travel Arrangements": ["Calendar Management", "Email Management", "Invoice & Expense Tracking", "Microsoft Office Suite", "Client Communication"],
  "Microsoft Office Suite": ["Google Workspace", "Email Management", "Calendar Management", "Document Formatting", "Excel (Advanced)"],
  "Google Workspace": ["Microsoft Office Suite", "Google Sheets (Advanced)", "Calendar Management", "Email Management", "Document Formatting"],
  "Project Management (Asana/Trello)": ["Notion", "Monday.com", "ClickUp", "Slack / Teams Communication", "Time Management"],
  "Slack / Teams Communication": ["Zoom / Google Meet Hosting", "Project Management (Asana/Trello)", "Client Communication", "Notion", "Google Workspace"],
  "Meeting Minutes & Notes": ["Calendar Management", "Email Management", "Transcription", "Microsoft Office Suite", "Document Formatting"],
  "Invoice & Expense Tracking": ["Bookkeeping", "QuickBooks", "Microsoft Office Suite", "Excel (Advanced)", "Invoicing & Billing"],
  "Research & Reporting": ["Market Research", "Document Formatting", "Google Workspace", "Microsoft Office Suite", "Data Storytelling"],
  "Document Formatting": ["Microsoft Office Suite", "Google Workspace", "Research & Reporting", "Presentation Design", "Meeting Minutes & Notes"],
  "Notion": ["Project Management (Asana/Trello)", "ClickUp", "Monday.com", "Slack / Teams Communication", "Google Workspace"],
  "Monday.com": ["Project Management (Asana/Trello)", "Notion", "ClickUp", "Slack / Teams Communication", "Time Management"],
  "ClickUp": ["Project Management (Asana/Trello)", "Notion", "Monday.com", "Slack / Teams Communication", "Time Management"],
  "Zoom / Google Meet Hosting": ["Slack / Teams Communication", "Calendar Management", "Meeting Minutes & Notes", "Client Communication", "Presentation Design"],
  "Time Management": ["Calendar Management", "Project Management (Asana/Trello)", "Client Communication", "Email Management", "Microsoft Office Suite"],
  "Client Communication": ["Email Management", "Slack / Teams Communication", "Time Management", "Negotiation", "Zoom / Google Meet Hosting"],
  "Transcription": ["Typing Speed (50+ WPM)", "Meeting Minutes & Notes", "English Proficiency", "Data Entry", "Document Formatting"],
  "Appointment Setting": ["Calendar Management", "Cold Calling", "Lead Generation", "Client Communication", "Email Management"],
  "File Management (Cloud)": ["Google Workspace", "Microsoft Office Suite", "Document Formatting", "Notion", "Slack / Teams Communication"],

  // ─── FIN: Finance & Accounting ───
  "Bookkeeping": ["QuickBooks", "Xero", "Accounts Payable / Receivable", "Bank Reconciliation", "Excel (Advanced)"],
  "QuickBooks": ["Bookkeeping", "Xero", "Payroll Processing", "Invoicing & Billing", "Excel (Advanced)"],
  "Xero": ["QuickBooks", "Bookkeeping", "Invoicing & Billing", "Bank Reconciliation", "Payroll Processing"],
  "SAP": ["ERP Systems (General)", "Financial Reporting", "Cost Accounting", "Budgeting & Forecasting", "Excel (Advanced)"],
  "Financial Analysis": ["Financial Modeling", "Excel (Advanced)", "Financial Reporting", "Budgeting & Forecasting", "Power BI"],
  "Financial Reporting": ["Financial Analysis", "Budgeting & Forecasting", "Excel (Advanced)", "SAP", "Auditing"],
  "Payroll Processing": ["QuickBooks", "Bookkeeping", "Tax Preparation (PH)", "Accounts Payable / Receivable", "Excel (Advanced)"],
  "Tax Preparation (PH)": ["Payroll Processing", "Bookkeeping", "CPA License (PH)", "Compliance & Regulatory", "QuickBooks"],
  "Accounts Payable / Receivable": ["Bookkeeping", "Invoicing & Billing", "Bank Reconciliation", "QuickBooks", "Excel (Advanced)"],
  "Budgeting & Forecasting": ["Financial Analysis", "Financial Reporting", "Financial Modeling", "Excel (Advanced)", "SAP"],
  "Auditing": ["Compliance & Regulatory", "Financial Reporting", "CPA License (PH)", "Bookkeeping", "Tax Preparation (PH)"],
  "Cost Accounting": ["Bookkeeping", "SAP", "Financial Analysis", "Budgeting & Forecasting", "ERP Systems (General)"],
  "Invoicing & Billing": ["Accounts Payable / Receivable", "QuickBooks", "Bookkeeping", "Xero", "Bank Reconciliation"],
  "Bank Reconciliation": ["Bookkeeping", "Accounts Payable / Receivable", "QuickBooks", "Xero", "Invoicing & Billing"],
  "CPA License (PH)": ["Auditing", "Tax Preparation (PH)", "Financial Reporting", "Financial Analysis", "Compliance & Regulatory"],
  "Financial Modeling": ["Financial Analysis", "Excel (Advanced)", "Budgeting & Forecasting", "Power BI", "Python (Data Science)"],
  "Insurance Processing": ["Compliance & Regulatory", "Accounts Payable / Receivable", "Invoicing & Billing", "Excel (Advanced)", "Data Entry"],
  "Compliance & Regulatory": ["Auditing", "Tax Preparation (PH)", "CPA License (PH)", "Data Governance", "HIPAA Compliance"],
  "ERP Systems (General)": ["SAP", "QuickBooks", "Financial Reporting", "Cost Accounting", "Budgeting & Forecasting"],
  "Cryptocurrency / Blockchain": ["Financial Analysis", "Python", "Financial Modeling", "Compliance & Regulatory", "Data Governance"],

  // ─── SALES: Sales & Business Dev ───
  "Lead Generation": ["Cold Calling", "Cold Emailing", "LinkedIn Outreach", "Salesforce CRM", "B2B Sales"],
  "Cold Calling": ["Lead Generation", "Telemarketing", "Cold Emailing", "Negotiation", "B2B Sales"],
  "Cold Emailing": ["Lead Generation", "Cold Calling", "LinkedIn Outreach", "Email Marketing", "Copywriting"],
  "Salesforce CRM": ["Pipedrive / CRM Tools", "Lead Generation", "Account Management", "Salesforce Service Cloud", "HubSpot"],
  "Pipedrive / CRM Tools": ["Salesforce CRM", "Lead Generation", "Account Management", "HubSpot", "B2B Sales"],
  "Negotiation": ["Cold Calling", "Account Management", "B2B Sales", "Sales Presentation", "Proposal Writing"],
  "B2B Sales": ["Lead Generation", "Account Management", "Cold Calling", "Negotiation", "Salesforce CRM"],
  "B2C Sales": ["Retail Sales", "Telemarketing", "Upselling / Cross-selling", "Social Media Management", "Cold Calling"],
  "Account Management": ["Salesforce CRM", "B2B Sales", "Negotiation", "Proposal Writing", "Client Communication"],
  "Sales Presentation": ["Proposal Writing", "Negotiation", "Presentation Design", "B2B Sales", "Account Management"],
  "LinkedIn Outreach": ["Lead Generation", "Cold Emailing", "B2B Sales", "Cold Calling", "Salesforce CRM"],
  "Proposal Writing": ["Sales Presentation", "Negotiation", "Account Management", "Copywriting", "B2B Sales"],
  "Telemarketing": ["Cold Calling", "Lead Generation", "Upselling / Cross-selling", "B2C Sales", "Neutral English Accent"],
  "Retail Sales": ["B2C Sales", "Upselling / Cross-selling", "Negotiation", "Customer Service (Voice)", "Account Management"],
  "Real Estate Sales": ["Negotiation", "Sales Presentation", "Lead Generation", "Account Management", "Proposal Writing"],

  // ─── ENG: Engineering & Technical ───
  "AutoCAD": ["Revit", "SolidWorks", "Civil Engineering", "Structural Analysis", "Project Management (Construction)"],
  "Revit": ["AutoCAD", "Civil Engineering", "Structural Analysis", "Project Management (Construction)", "Quantity Surveying"],
  "SolidWorks": ["AutoCAD", "Mechanical Engineering", "3D Modeling (Blender)", "Electronics / PCB Design", "MATLAB"],
  "Civil Engineering": ["AutoCAD", "Revit", "Structural Analysis", "Project Management (Construction)", "Quantity Surveying"],
  "Electrical Engineering": ["PLC Programming", "Electronics / PCB Design", "Electrical Installation", "AutoCAD", "IoT (Internet of Things)"],
  "Mechanical Engineering": ["SolidWorks", "AutoCAD", "HVAC Design", "MATLAB", "Quality Control / Inspection"],
  "Project Management (Construction)": ["Civil Engineering", "AutoCAD", "Quantity Surveying", "Safety Management (OSHA)", "Six Sigma / Lean"],
  "Structural Analysis": ["Civil Engineering", "AutoCAD", "Revit", "MATLAB", "Project Management (Construction)"],
  "HVAC Design": ["Mechanical Engineering", "AutoCAD", "HVAC Installation & Repair", "Electrical Engineering", "SolidWorks"],
  "Quality Control / Inspection": ["Six Sigma / Lean", "Safety Management (OSHA)", "Project Management (Construction)", "Mechanical Engineering", "Auditing"],
  "PLC Programming": ["Electrical Engineering", "IoT (Internet of Things)", "Robotics", "Electronics / PCB Design", "MATLAB"],
  "Six Sigma / Lean": ["Quality Control / Inspection", "Project Management (Construction)", "Safety Management (OSHA)", "Supply Chain Management", "Mechanical Engineering"],
  "Safety Management (OSHA)": ["Quality Control / Inspection", "Project Management (Construction)", "Six Sigma / Lean", "Civil Engineering", "HVAC Design"],
  "Renewable Energy": ["Electrical Engineering", "Civil Engineering", "Mechanical Engineering", "IoT (Internet of Things)", "HVAC Design"],
  "Quantity Surveying": ["Civil Engineering", "Project Management (Construction)", "AutoCAD", "Revit", "Budgeting & Forecasting"],
  "GIS / Mapping": ["AutoCAD", "Civil Engineering", "Python", "Data Cleaning & Wrangling", "Renewable Energy"],
  "MATLAB": ["Python", "Structural Analysis", "Mechanical Engineering", "SolidWorks", "Statistical Analysis"],
  "IoT (Internet of Things)": ["PLC Programming", "Electrical Engineering", "Robotics", "Python", "Electronics / PCB Design"],
  "Robotics": ["PLC Programming", "IoT (Internet of Things)", "Python", "Mechanical Engineering", "Electronics / PCB Design"],
  "Electronics / PCB Design": ["Electrical Engineering", "PLC Programming", "SolidWorks", "IoT (Internet of Things)", "Robotics"],

  // ─── HC: Healthcare ───
  "Nursing (RN License)": ["First Aid / BLS", "Electronic Health Records (EHR)", "HIPAA Compliance", "Caregiving", "Telemedicine Support"],
  "Medical Technology": ["Electronic Health Records (EHR)", "Medical Coding (ICD-10)", "HIPAA Compliance", "Pharmacy", "Nursing (RN License)"],
  "Pharmacy": ["Medical Technology", "HIPAA Compliance", "Nutrition & Dietetics", "Electronic Health Records (EHR)", "Medical Billing"],
  "Caregiving": ["Nursing (RN License)", "First Aid / BLS", "Mental Health Support", "Physical Therapy", "Nutrition & Dietetics"],
  "Medical Coding (ICD-10)": ["Medical Billing", "Electronic Health Records (EHR)", "HIPAA Compliance", "Medical Transcription", "Data Entry"],
  "Medical Billing": ["Medical Coding (ICD-10)", "Electronic Health Records (EHR)", "HIPAA Compliance", "Accounts Payable / Receivable", "Insurance Processing"],
  "HIPAA Compliance": ["Electronic Health Records (EHR)", "Medical Coding (ICD-10)", "Medical Billing", "Compliance & Regulatory", "Nursing (RN License)"],
  "Electronic Health Records (EHR)": ["HIPAA Compliance", "Medical Coding (ICD-10)", "Medical Billing", "Nursing (RN License)", "Telemedicine Support"],
  "Telemedicine Support": ["Electronic Health Records (EHR)", "Nursing (RN License)", "HIPAA Compliance", "Zoom / Google Meet Hosting", "Mental Health Support"],
  "First Aid / BLS": ["Nursing (RN License)", "Caregiving", "Safety Management (OSHA)", "Physical Therapy", "Mental Health Support"],
  "Dental Assisting": ["First Aid / BLS", "HIPAA Compliance", "Electronic Health Records (EHR)", "Caregiving", "Nursing (RN License)"],
  "Physical Therapy": ["Caregiving", "Nursing (RN License)", "First Aid / BLS", "Nutrition & Dietetics", "Mental Health Support"],
  "Nutrition & Dietetics": ["Physical Therapy", "Caregiving", "Pharmacy", "Nursing (RN License)", "Mental Health Support"],
  "Mental Health Support": ["Caregiving", "Student Counseling", "Telemedicine Support", "Nursing (RN License)", "Physical Therapy"],
  "Medical Transcription": ["Medical Coding (ICD-10)", "Transcription", "Typing Speed (50+ WPM)", "Data Entry", "Electronic Health Records (EHR)"],

  // ─── EDU: Education & Training ───
  "Teaching (K-12)": ["Curriculum Development", "Instructional Design", "Assessment Design", "Special Education (SPED)", "LMS Administration (Moodle/Canvas)"],
  "ESL / TESOL Teaching": ["Online Tutoring", "English Proficiency", "Teaching (K-12)", "Curriculum Development", "Academic Writing"],
  "Online Tutoring": ["ESL / TESOL Teaching", "Teaching (K-12)", "LMS Administration (Moodle/Canvas)", "Zoom / Google Meet Hosting", "E-Learning Content Creation"],
  "Instructional Design": ["E-Learning Content Creation", "LMS Administration (Moodle/Canvas)", "Curriculum Development", "Assessment Design", "Corporate Training"],
  "LMS Administration (Moodle/Canvas)": ["Instructional Design", "E-Learning Content Creation", "Online Tutoring", "Corporate Training", "Curriculum Development"],
  "Curriculum Development": ["Teaching (K-12)", "Instructional Design", "Assessment Design", "E-Learning Content Creation", "Academic Writing"],
  "Corporate Training": ["Instructional Design", "LMS Administration (Moodle/Canvas)", "E-Learning Content Creation", "Presentation Design", "Sales Presentation"],
  "E-Learning Content Creation": ["Instructional Design", "LMS Administration (Moodle/Canvas)", "Curriculum Development", "Corporate Training", "Canva"],
  "Assessment Design": ["Curriculum Development", "Teaching (K-12)", "Instructional Design", "Statistical Analysis", "A/B Testing"],
  "Special Education (SPED)": ["Teaching (K-12)", "Student Counseling", "Curriculum Development", "Assessment Design", "Caregiving"],
  "Student Counseling": ["Mental Health Support", "Special Education (SPED)", "Teaching (K-12)", "Caregiving", "Assessment Design"],
  "Academic Writing": ["Research & Reporting", "Content Writing", "Technical Writing", "ESL / TESOL Teaching", "Curriculum Development"],

  // ─── TRADE: Skilled Trades & Logistics ───
  "Warehouse Management": ["Inventory Management", "Supply Chain Management", "Forklift Operation", "Procurement", "Shipping / Freight Coordination"],
  "Supply Chain Management": ["Warehouse Management", "Inventory Management", "Procurement", "Shipping / Freight Coordination", "Six Sigma / Lean"],
  "Inventory Management": ["Warehouse Management", "Supply Chain Management", "Procurement", "E-Commerce Management", "Excel (Advanced)"],
  "Forklift Operation": ["Warehouse Management", "Heavy Equipment Operation", "Safety Management (OSHA)", "Inventory Management", "Supply Chain Management"],
  "Delivery / Courier Services": ["Last-Mile Logistics (Lazada/Shopee)", "Shipping / Freight Coordination", "Warehouse Management", "Time Management", "Supply Chain Management"],
  "Electrical Installation": ["Electrical Engineering", "HVAC Installation & Repair", "Plumbing", "Safety Management (OSHA)", "PLC Programming"],
  "Plumbing": ["Electrical Installation", "HVAC Installation & Repair", "Safety Management (OSHA)", "Welding", "Automotive Repair"],
  "Welding": ["Plumbing", "HVAC Installation & Repair", "Electrical Installation", "Automotive Repair", "Heavy Equipment Operation"],
  "HVAC Installation & Repair": ["HVAC Design", "Electrical Installation", "Plumbing", "Welding", "Safety Management (OSHA)"],
  "Automotive Repair": ["Welding", "Electrical Installation", "Mechanical Engineering", "Safety Management (OSHA)", "Heavy Equipment Operation"],
  "Food Handling / HACCP": ["Safety Management (OSHA)", "Quality Control / Inspection", "Warehouse Management", "Inventory Management", "Supply Chain Management"],
  "Heavy Equipment Operation": ["Forklift Operation", "Safety Management (OSHA)", "Warehouse Management", "Welding", "Automotive Repair"],
  "Procurement": ["Supply Chain Management", "Inventory Management", "Warehouse Management", "Negotiation", "Excel (Advanced)"],
  "Shipping / Freight Coordination": ["Supply Chain Management", "Warehouse Management", "Delivery / Courier Services", "Last-Mile Logistics (Lazada/Shopee)", "Inventory Management"],
  "Last-Mile Logistics (Lazada/Shopee)": ["Delivery / Courier Services", "Shipping / Freight Coordination", "Warehouse Management", "E-Commerce Management", "Inventory Management"],
};
